export const dataListStuden = [
  {
    id: 1,
    name: "Phan Van khai",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
  {
    id: 2,
    name: "Phan Van Khanh",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
  {
    id: 3,
    name: "Phan Van son",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
  {
    id: 4,
    name: "Phan Van anh",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
  {
    id: 5,
    name: "Phan Van khai 1",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
  {
    id: 6,
    name: "Phan Van khai 2",
    class: "16DTHC1",
    key: "K16",
    description: "yeu mau hong",
    status: true,
  },
];
